apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RHOAI-dev
  description: |
      RHOAI development dashboard for managing and monitoring RHOAI instances.
  links:
    - url: https://backstage.io
      title: Project Homepage
      icon: home
  annotations:
    github.com/project-slug: 'red-hat-data-services/kserve'
    #jenkins.io/job-full-name: 'my-react-app-pipeline'
spec:
  type: service
  lifecycle: experimental
  owner: group:default/rhoai
